name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.hhimanshuu1 }}
          password: ${{ secrets.dckr_pat_9h }}

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: 'table'
          exit-code: '0'

      - name: Push Docker Image
        run: |
          docker tag myapp:latest hhimanshuu1/myapp:latest
          docker push hhimanshuu1/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull hhimanshuu1/myapp:latest
            docker stop myapp || true && docker rm myapp || true
            docker run -d -p 80:80 --name myapp hhimanshuu1/myapp:latest
